# 예외 처리하기

* 자바스크립트에는 throw 문과 try - catch - finally 문이 존재합니다.

* 개발자가 의도한 에러인 경우 throw 문을 사용합니다.

* throw 문은 고의로 에러를 발생시켜 예외상황을 알리는 역할을 합니다.

```javascript
function checkNumber(val){
  if(typeof val !== 'number') throw '유효하지 않은 값입니다.';
  console.log('숫자형 값으로 확인되었습니다.');
}

checkNumber(100);
checkNumber('tree');
console.log('완료');
```

```
숫자형 값으로 확인되었습니다.

.../foo.js:2
  if(typeof val !== 'number') throw '유효하지 않은 값입니다.;
                              ^
유효하지 않은 값입니다.
```

* throw 문은 에러를 발생시킨 것이므로 프로그램이 중단되는 것을 막을 수 없습니다.

* 이에 대한 대응책이 try - catch - finally 문 입니다.

* try - catch - finally 문은 프로그램 중단 상황을 방지 해주는 효과가 있습니다.

```javacript
function checkNumber(val){
  if(typeof val !== 'number') throw '유효하지 않은 값입니다.';
  console.log('숫자형 값으로 확인되었습니다.');
}

try{
  checkNumber(100);
  checkNumber('tree');
}catch(e){
  console.log('에러가 발생했습니다 : ${e}');
}finally{
  console.log('완료');
}
```

```
숫자형 값으로 확인되었습니다.
에러가 발생했습니다 : 유효하지 않은 값입니다.

```
